using UnityEngine;
using System.Collections.Generic;
using System;

namespace Revenga.VSM
{
    [Serializable]
    public class VSMManager
    {
        /// <summary>
        /// Generated by Guid.NewGuid();
        /// </summary>
        [SerializeField] public string Id;

        [SerializeField] public string ManagerName = "";
        [SerializeField] public string CurrentStateName = "";
        [SerializeField] public string DefaultStateName = "";
        [SerializeField] public int LayerIndex = -1;

        [SerializeField] public List<VSMState> States = new List<VSMState>();

        public VSMManager()
        {
            if (string.IsNullOrEmpty(Id))
            {
                Id = Guid.NewGuid().ToString();
            }
        }
    }
}
