using System;
using System.Collections.Generic;
using UnityEngine;

namespace Revenga.VSM
{
    [System.Serializable]
    public class VSMState
    {
        /// <summary>
        /// Generated by Guid.NewGuid();
        /// </summary>
        [SerializeField]
        public string Id;

        public string StateName;
        public string AnimationClipName;
        public float Time;
        public List<VSMStateProperty> Properties = new List<VSMStateProperty>();

        public VSMState()
        {
            if (string.IsNullOrEmpty(Id))
                Id = Guid.NewGuid().ToString();
        }
    }

    [System.Serializable]
    public class VSMStateProperty
    {
        public enum ParamType
        {
            PropertyName = 0,
            Path = 1,
            Value = 2,
            ObjectValue = 3,
            BoolValue = 4,
            PropertyType = 5
        }

        [System.Serializable]
        public enum VSMStatePropertyType
        {
            Float,
            Bool,
            Object
        }
        
        public string N; // Property Name
        public string F; // Struct Field
        public string P; // Path to GameObject transform
        public float V; // Float Value
        [SerializeField]
        public UnityEngine.Object OV;
        public bool BV;
        public VSMStatePropertyType T;
        [SerializeField]
        public string C; // Type name of the Component
    }
}
