using System;
using System.Collections.Generic;
using UnityEngine;

namespace Revenga.VSM
{
    [Serializable]
    public class VSMState
    {
        /// <summary>
        /// Generated by Guid.NewGuid();
        /// </summary>
        [SerializeField] public string Id;

        public string StateName;
        public float Time;
        public List<VSMStateProperty> Properties = new List<VSMStateProperty>();

        public VSMState()
        {
            if (string.IsNullOrEmpty(Id))
            {
                Id = Guid.NewGuid().ToString();
            }
        }
    }

    [Serializable]
    public class VSMStateProperty
    {
        [SerializeField] public string N; // Property Name
        [SerializeField] public string P; // Path to GameObject transform

        [SerializeField] public Vector4 O;
        [SerializeField] public string C; // Type name of the Component
    }
}
